name: news_app_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4

  json_serializable: ^6.3.1
  json_annotation: ^4.5.0

  flutter_bloc: ^8.0.1

  webview_flutter: ^3.0.4

  cached_network_image: ^3.2.1

  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/no_image.png


  uses-material-design: true
